# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 47b81e1d92ca3172b1f6b45520d49ad184c1f9784c75d7e8def46d07a410444180d967665420f4ddd99df5770061d26958f6a98794573ba4378963ff8ee3c56c

test:
  secret_key_base: 30424417a1702e279fac4a81775cef8a4e4dacf5e7e457b5db103c62ba404605b14f771c58957d6e5bc229c677f99b91c498b9601649d25a6ee1f55e746768b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
